package com.xerxes.videodroid

import android.content.Context
import android.webkit.CookieManager
import java.io.File

/** On-device Netscape cookie file for yt-dlp. Never leave the phone. */
object XCookies {
    const val FILE_NAME = "cookies.txt"

    fun file(context: Context): File = File(context.filesDir, FILE_NAME)

    fun exists(context: Context): Boolean {
        val f = file(context)
        return f.isFile && f.length() > 0
    }

    fun looksLoggedIn(): Boolean {
        val cm = CookieManager.getInstance()
        return listOf("https://x.com/", "https://twitter.com/").any { url ->
            val c = cm.getCookie(url) ?: return@any false
            c.contains("auth_token=")
        }
    }

    /** Write CookieManager cookies as Netscape HTTP Cookie File (MODE_PRIVATE via filesDir). */
    fun exportFromWebView(context: Context): Boolean {
        val cm = CookieManager.getInstance()
        cm.flush()
        val lines = ArrayList<String>()
        lines.add("# Netscape HTTP Cookie File")
        lines.add("# This file was generated by VideoDroid. Do not edit.")
        lines.add("")
        val urls = listOf(
            "https://x.com/",
            "https://www.x.com/",
            "https://twitter.com/",
            "https://www.twitter.com/",
            "https://mobile.twitter.com/",
            "https://api.x.com/",
            "https://api.twitter.com/",
        )
        val seen = HashSet<String>()
        for (url in urls) {
            val raw = cm.getCookie(url) ?: continue
            val host = hostOf(url) ?: continue
            val domain = if (host.startsWith(".")) host else ".$host"
            for (part in raw.split(";")) {
                val eq = part.indexOf('=')
                if (eq <= 0) continue
                val name = part.substring(0, eq).trim()
                val value = part.substring(eq + 1).trim()
                if (name.isEmpty()) continue
                val key = "$domain|$name"
                if (!seen.add(key)) continue
                // domain, includeSubdomains, path, secure, expiry (0 = session), name, value
                lines.add(listOf(domain, "TRUE", "/", "TRUE", "0", name, value).joinToString("\t"))
            }
        }
        if (seen.isEmpty()) return false
        val f = file(context)
        f.writeText(lines.joinToString("\n") + "\n")
        return f.length() > 0
    }

    fun clear(context: Context) {
        file(context).delete()
        val cm = CookieManager.getInstance()
        cm.removeAllCookies(null)
        cm.flush()
    }

    private fun hostOf(url: String): String? {
        return try {
            java.net.URI(url).host
        } catch (_: Throwable) {
            null
        }
    }
}
